version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8085:8085"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27025:27025"