version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8025:80"
    depends_on:
      - mongo
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PORT=80
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - app_network
    ports:
      - "27017"
networks:
  app_network: